- name: Create jenkins Jobs
  hosts: localhost
  roles:
    - jenkins
  vars:
    folders:
      - { folder_name: "CI-Pipelines" }
      - { folder_name: "Infra-Jobs" }
    mjobs:
      - { job_name: "cart", repo_name: "https://github.com/Revanthsatyam/cart.git", folder_name: "CI-Pipelines" }
      - { job_name: "catalogue", repo_name: "https://github.com/Revanthsatyam/catalogue.git", folder_name: "CI-Pipelines" }
      - { job_name: "user", repo_name: "https://github.com/Revanthsatyam/user.git", folder_name: "CI-Pipelines" }
      - { job_name: "payment", repo_name: "https://github.com/Revanthsatyam/payment.git", folder_name: "CI-Pipelines" }
      - { job_name: "shipping", repo_name: "https://github.com/Revanthsatyam/shipping.git", folder_name: "CI-Pipelines" }
      - { job_name: "frontend", repo_name: "https://github.com/Revanthsatyam/frontend.git", folder_name: "CI-Pipelines" }
    sjobs:
      - { job_name: "roboshop-terraform", repo_name: "https://github.com/Revanthsatyam/roboshop-jenkins.git", folder_name: "Infra-Jobs" }