- name: Copy Config - {{ item.folder_name }}
  ansible.builtin.template:
    src: folder.xml
    dest: /tmp/folder.xml

- name: Create Job - {{ item.folder_name }}
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/folder.xml') }}"
    name: "{{ item.folder_name }}"
    password: Devops@74
    url: http://172.31.32.213:8080
    user: admin