- name: Create Multibranch Pipeline Jobs
  ansible.builtin.include_tasks:
    file: mjob.yml
  loop: "{{ mjobs }}"

- name: Create Singlebranch Pipeline jobs
  ansible.builtin.include_tasks:
    file: sjob.yml
  loop: "{{ sjobs }}"