- name: Create Job For Singlebranch Pipeline
  ansible.builtin.include_tasks:
    file: sjob.yml
  loop: "{{ sjobs }}"

- name: Create Job For Multibranch Pipeline
  ansible.builtin.include_tasks:
    file: mjob.yml
  loop: "{{ mjobs }}"