- name: Create Multibranch Pipeline Jobs
  ansible.builtin.include_tasks:
    file: mjob.xml
  loop: "{{ mjobs }}"

- name: Create Singlebranch Pipeline jobs
  ansible.builtin.include_tasks:
    file: sjob.xml
  loop: "{{ sjobs }}"