- name: Copy Config Multibranch pipeline
  ansible.builtin.template:
    src: mjob.xml
    dest: /tmp/mjob.xml

- name: Create A Jenkins Job For Multibranch pipeline
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/mjob.xml') }}"
    name: mjob
    password: Devops@74
    url: http://172.31.32.213:8080
    user: admin
