- name: Copy Config File Of Multi Branch pipeline
  ansible.builtin.template:
    src: sjob.xml
    dest: /tmp/sjob.xml

- name: Create Multi Branch pipeline job
  community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/sjob.xml') }}"
    name: sjob
    password: Devops@74
    url: http://172.31.32.213:8080
    user: admin